name: Build and Deploy
env:
  CI: false
  GITHUB_USERNAME: ${{ github.repository_owner }}
  REACT_APP_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This is automatically set by GitHub Actions
  USE_GITHUB_DATA: "true"
  MEDIUM_USERNAME: "onsreddy2002" # Change this to your Medium username

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: "0 12 * * 1" # Scheduled weekly run

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Node.js 🔧
        uses: actions/setup-node@v3
        with:
          node-version: '22.9.0'  # ✅ Updated Node.js version
          cache: 'npm'

      - name: Update npm 🚀
        run: npm install -g npm@11.1.0  # ✅ Updated npm version

      - name: Install and Build 🔧
        run: |
          npm install
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub token for authentication
          BRANCH: gh-pages # The branch to deploy to
          FOLDER: build # The folder to deploy
